# Generated by nixos-generate-config / nixos-generate-config で生成
# Regeneration overwrites this file; edit /etc/nixos/configuration.nix instead. / 再生成で上書きされるため、変更は /etc/nixos/configuration.nix へ。
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/ac7a90b9-be80-4b18-b35e-d17f718fee0d";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/BE32-3794";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # DHCP defaults / DHCP 既定値
  # Works with networkd, but per-interface settings are recommended. / networkd でも利用可能だが、個別設定と併用推奨。
  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.enableAllFirmware = true;

  # Graphics configuration / グラフィックス設定
  # Use Mesa-based drivers for AMD GPUs. / AMD GPU 向けに Mesa ベースのドライバーを使用。
  hardware.graphics = {
    enable32Bit = true;
    extraPackages = with pkgs; [
      libva
      libva-vdpau-driver
      libvdpau-va-gl
    ];
    extraPackages32 = with pkgs.pkgsi686Linux; [
      libva
      libva-vdpau-driver
      libvdpau-va-gl
    ];
  };
}
