name: Update Code Cursor Package

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  update-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run update script
        run: |
          echo "Running update script..."
          cd pkgs/code-cursor
          ./update.sh
          echo "Update script finished."

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(code-cursor): Update to latest version"
          title: "chore(code-cursor): Update to latest version"
          body: |
            Automated update of the code-cursor package to the latest version.
            Please review the changes and merge if everything looks good.
          branch: "chore/update-code-cursor"
          delete-branch: true # Deletes the branch once the PR is merged or closed
          labels: automated pr, nix, package update
          assignees: ${{ github.actor }} # Assigns the user who triggered the workflow (if manual)
          # Optional: Add reviewers
          # reviewers: user1,user2