name: Update Packages

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  update-code-cursor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run update script
        run: |
          echo "Running code-cursor update script..."
          cd pkgs/code-cursor
          ./update.sh
          echo "Update script finished."

      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check-changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(code-cursor): Update to latest version"
          title: "chore(code-cursor): Update to latest version"
          body: |
            Automated update of the code-cursor package to the latest version.
            Please review the changes and merge if everything looks good.
          branch: "chore/update-code-cursor"
          delete-branch: true
          labels: automated pr, nix, package update

  update-ccmanager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup GitHub CLI
        run: |
          echo "GitHub CLI is pre-installed in GitHub Actions runners"

      - name: Run update script
        run: |
          echo "Running ccmanager update script..."
          cd pkgs/ccmanager
          ./update.sh
          echo "Update script finished."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check-changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(ccmanager): Update to latest version"
          title: "chore(ccmanager): Update to latest version"
          body: |
            Automated update of the ccmanager package to the latest version.
            Please review the changes and merge if everything looks good.
          branch: "chore/update-ccmanager"
          delete-branch: true
          labels: automated pr, nix, package update

  update-codex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run update script
        run: |
          echo "Running codex update script..."
          cd pkgs/codex
          chmod +x ./update.sh
          ./update.sh
          echo "Update script finished."

      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check-changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(codex): Update to latest rust tag"
          title: "chore(codex): Update to latest rust tag"
          body: |
            Automated update of the Codex (Rust) overlay in flake.nix to the latest rust tag.
            This also refreshes src sha256 and cargo vendor hash.
          branch: "chore/update-codex"
          delete-branch: true
          labels: automated pr, nix, package update
